theme: jekyll-theme-minimal
# title: Core Portal Deployment Procedures
title: false
logo: /static/img/TACC_400x400.png
description: Detailed documentation and checklists for deploying the TACC ACI-WMA Core v2 Portal.
